apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
  labels:
    app: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
      - name: crud-app
        image: harikrishnan3112/java-sb:v1.0.3 # {"$imagepolicy": "flux-system:podinfo"}
